import fs from 'fs';
import path from 'path';
import os from 'os';
import { execFileSync } from 'node:child_process';
import { db, productStmts, phaseStmts, knowledgeStmts, portfolioStmts, goalStmts } from '../db';

// ── Forward-reference setters ────────────────────────────
// These break circular dependencies between products.ts and server.js.
// server.js calls the setters at startup to inject its own functions.

let createGoal: (description: string, projectPath: string, autoExecute?: boolean, parentGoalId?: string | null, goalType?: string, planningModel?: string | null) => string;
let broadcast: ((msg: Record<string, unknown>) => void) | null = null;
let loadConfig: () => any;

export function setCreateGoalFn(fn: typeof createGoal) {
    createGoal = fn;
}

export function setBroadcastFn(fn: typeof broadcast) {
    broadcast = fn;
}

export function setLoadConfigFn(fn: typeof loadConfig) {
    loadConfig = fn;
}

// ── Helper ───────────────────────────────────────────────

function generateId(): string {
    return Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 8);
}

// ── Constants ────────────────────────────────────────────

export const PIPELINE_PHASES = ['research', 'design', 'architecture', 'build', 'test', 'document', 'deploy'];
export const GATED_PHASES = ['design', 'architecture', 'build', 'deploy'];

// ── createProduct ────────────────────────────────────────

/**
 * Create a new product pipeline. Creates the product record, 7 phase records,
 * a project directory, and kicks off the research phase.
 */
export function createProduct(name: string, seed: string, config: Record<string, any> = {}) {
    const productId = generateId();
    const now = new Date().toISOString();
    const safeName = name.replace(/[^a-zA-Z0-9_-]/g, '-').toLowerCase();
    const projectDir = path.join(os.homedir(), 'Projects', safeName);

    // Create product record
    productStmts.insert.run(productId, name, seed, projectDir, 'research', 'active', now, JSON.stringify(config));

    // Create 7 phase records
    for (const phase of PIPELINE_PHASES) {
        phaseStmts.insert.run(generateId(), productId, phase, 'pending');
    }

    // Create project directory with basic structure
    try {
        if (!fs.existsSync(projectDir)) {
            fs.mkdirSync(projectDir, { recursive: true });
        }
        const claudeMd = `# ${name}\n\n> Auto-generated by Hortus Arbor Nostra Product Pipeline\n\n## Seed\n\n${seed}\n`;
        const readmeMd = `# ${name}\n\nGenerated by Hortus Arbor Nostra.\n`;
        fs.writeFileSync(path.join(projectDir, 'CLAUDE.md'), claudeMd);
        fs.writeFileSync(path.join(projectDir, 'README.md'), readmeMd);
        productStmts.updatePath.run(projectDir, productId);
    } catch (err: any) {
        console.error(`[Pipeline] Failed to create project directory for ${name}:`, err.message);
    }

    // Register as a project in portfolio
    try {
        const existingProject = (db as any).prepare('SELECT id FROM projects WHERE path = ?').get(projectDir);
        if (!existingProject) {
            portfolioStmts.upsert.run(safeName, projectDir, 'Product pipeline: ' + name, 'active', null, now);
        }
    } catch (err: any) {
        console.error(`[Pipeline] Failed to register project:`, err.message);
    }

    // Broadcast pipeline creation
    if (broadcast) {
        broadcast({ type: 'pipeline_created', productId, name, phases: PIPELINE_PHASES.length });
    }

    // Kick off research phase (not gated)
    executePhase(productId, 'research');

    console.log(`[Pipeline] Created product "${name}" (${productId}), research phase started`);
    return productId;
}

// ── getKnowledgeSummary ──────────────────────────────────

/**
 * Get a summary of accumulated knowledge for a product (capped at 2000 chars).
 */
function getKnowledgeSummary(productId: string): string {
    const entries = knowledgeStmts.getByProduct.all(productId);
    if (entries.length === 0) return '';

    let summary = 'Previous findings:\n';
    for (const entry of entries) {
        const line = `- [${(entry as any).category}] ${(entry as any).title}: ${(entry as any).content}\n`;
        if (summary.length + line.length > 2000) {
            summary += '... (truncated)\n';
            break;
        }
        summary += line;
    }
    return summary;
}

// ── getResearchSubagents ─────────────────────────────────

/**
 * Generate focused research subagent prompts for the 6 research areas.
 */
export function getResearchSubagents(productName: string, seed: string) {
    return [
        {
            area: 'market',
            title: `Market Research: ${productName}`,
            description: `Market research for ${productName}. Seed idea: ${seed}

Research objectives:
- Market size and growth trends (TAM/SAM/SOM estimates)
- Target audience demographics and pain points
- Customer willingness to pay and pricing expectations
- Revenue model opportunities (freemium, subscription, one-time, usage-based)
- Market entry barriers and timing considerations
- Geographic considerations (AU/US/EU markets)

Deliverables: market size estimates, 3-5 target customer personas, recommended revenue model with pricing ranges, go-to-market strategy recommendations.`
        },
        {
            area: 'technical',
            title: `Technical Feasibility: ${productName}`,
            description: `Technical feasibility assessment for ${productName}. Seed idea: ${seed}

Research objectives:
- Required APIs, libraries, and frameworks (availability, licensing, maturity)
- Implementation complexity per major component
- Infrastructure requirements (hosting, storage, compute, networking)
- Third-party service dependencies (payment, auth, notifications, analytics)
- Technical risks and mitigation strategies
- Development time estimates per component

Deliverables: technology assessment matrix, implementation roadmap with estimates, risk register with mitigations, proof-of-concept recommendations.`
        },
        {
            area: 'competitive',
            title: `Competitive Analysis: ${productName}`,
            description: `Competitive landscape analysis for ${productName}. Seed idea: ${seed}

Research objectives:
- Direct competitors (products solving the same problem)
- Indirect competitors (alternative approaches customers use today)
- Feature comparison matrix (what they offer, what they lack)
- Pricing analysis (monetisation models, pricing tiers)
- Market positioning (messaging, target audience, differentiators)
- Gaps and opportunities (underserved needs, emerging trends)

Deliverables: competitive matrix with 5-10 key competitors, feature gap analysis, pricing comparison, recommended positioning strategy.`
        },
        {
            area: 'practices',
            title: `Best Practices: ${productName}`,
            description: `Engineering best practices research for ${productName}. Seed idea: ${seed}

Research objectives:
- Design patterns for this problem domain (architecture, data models)
- Reference implementations and open-source examples
- Documentation and API design standards
- Performance optimisation techniques relevant to this domain
- Security best practices (authentication, authorisation, data protection)
- Testing strategies (unit, integration, E2E patterns)

Deliverables: recommended design patterns with rationale, reference repositories, security checklist, testing strategy template.`
        },
        {
            area: 'regulatory',
            title: `Regulatory Requirements: ${productName}`,
            description: `Regulatory and compliance research for ${productName}. Seed idea: ${seed}

Research objectives:
- Legal requirements by jurisdiction (AU, US, EU)
- Industry standards and certifications (ISO, SOC2, etc.)
- Data privacy laws (GDPR, CCPA, Australian Privacy Act)
- Accessibility requirements (WCAG, ADA)
- Terms of service and privacy policy considerations
- Insurance and liability considerations

Deliverables: compliance checklist by jurisdiction, required certifications with timeline, legal document requirements, risk assessment.`
        },
        {
            area: 'ux',
            title: `UX Pattern Research: ${productName}`,
            description: `UX patterns and design research for ${productName}. Seed idea: ${seed}

Research objectives:
- UI patterns for this product category (dashboards, forms, navigation)
- Design inspiration from best-in-class examples
- Interaction patterns (mobile, desktop, touch, keyboard)
- Accessibility patterns (screen readers, keyboard navigation)
- Responsive design strategies and breakpoints
- Onboarding flow examples and user activation patterns

Deliverables: UI pattern library references, recommended design system or component library, interaction flow diagrams, onboarding checklist.`
        }
    ];
}

// ── getDesignSubagents ───────────────────────────────────

/**
 * Generate focused design subagent prompts for the 6 design artifact areas.
 */
export function getDesignSubagents(productName: string, seed: string, knowledgeSummary: string) {
    const ctx = knowledgeSummary ? `\n\nContext from research phase:\n${knowledgeSummary}` : '';
    return [
        {
            area: 'requirements',
            title: `Requirements: ${productName}`,
            description: `Requirements specification for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- User stories in "As a [role], I want [feature], so that [benefit]" format (15-30 stories)
- Acceptance criteria for each story (Given/When/Then)
- Functional requirements grouped by feature area
- Non-functional requirements (performance, scalability, security, availability)
- Edge cases and error scenarios
- Priority classification (must-have, should-have, nice-to-have)
- Out-of-scope items explicitly listed`
        },
        {
            area: 'datamodel',
            title: `Data Model: ${productName}`,
            description: `Data model design for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- Entity-relationship diagram description (entities, attributes, relationships)
- Database schema (tables, columns, types, constraints, indices)
- Data validation rules per field
- Migration plan (initial schema creation SQL)
- Seed data requirements
- Data retention and archival policy
- Estimated storage growth projections`
        },
        {
            area: 'api',
            title: `API Specification: ${productName}`,
            description: `API contract specification for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- REST endpoint listing (method, path, description)
- Request/response schemas for each endpoint (JSON examples)
- Authentication and authorisation model (JWT, API keys, OAuth, etc.)
- Error response format and standard error codes
- Rate limiting and pagination strategy
- Webhook/event specifications if applicable
- API versioning strategy`
        },
        {
            area: 'ux',
            title: `UX Design: ${productName}`,
            description: `UX and wireframe design for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- Page/screen inventory (list all views with purpose)
- Wireframe descriptions for each page (layout, components, content areas)
- Component hierarchy (reusable UI components)
- Navigation structure and information architecture
- Responsive breakpoints and mobile adaptation strategy
- Design system recommendations (colours, typography, spacing)
- Onboarding flow (first-time user experience)`
        },
        {
            area: 'interactions',
            title: `Interaction Design: ${productName}`,
            description: `Interaction and state design for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- User flow diagrams (Mermaid format) for key journeys
- State management patterns (what state lives where)
- Form validation flows with error message specifications
- Loading states, empty states, and error states for each view
- Real-time update patterns (polling, WebSocket, SSE)
- Optimistic UI patterns where applicable
- Transition and animation specifications`
        },
        {
            area: 'accessibility',
            title: `Accessibility Design: ${productName}`,
            description: `Accessibility and compliance design for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- WCAG 2.1 AA compliance checklist with implementation notes
- Keyboard navigation map (tab order, shortcuts, focus management)
- Screen reader annotations (ARIA roles, labels, live regions)
- Colour contrast verification plan
- Touch target sizing for mobile (minimum 44x44px)
- Alternative text strategy for images and media
- Reduced motion and preference-based adaptations`
        }
    ];
}

// ── getArchitectureSubagents ─────────────────────────────

/**
 * Generate focused architecture subagent prompts for the 6 architecture areas.
 */
export function getArchitectureSubagents(productName: string, seed: string, knowledgeSummary: string) {
    const ctx = knowledgeSummary ? `\n\nContext from research and design phases:\n${knowledgeSummary}` : '';
    return [
        {
            area: 'stack',
            title: `Technology Stack: ${productName}`,
            description: `Technology stack selection for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- Primary programming language(s) with rationale
- Backend framework selection (Express, Fastify, Hono, etc.) with trade-offs
- Frontend framework selection (React, Vue, Svelte, etc.) with trade-offs
- Database selection (PostgreSQL, SQLite, MongoDB, etc.) with rationale
- Runtime environment (Node.js, Deno, Bun, etc.)
- Key libraries for common concerns (auth, validation, testing, logging)
- Version requirements and compatibility matrix
- Rationale document explaining why each choice was made`
        },
        {
            area: 'structure',
            title: `Project Structure: ${productName}`,
            description: `Project structure design for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- Complete directory layout with purpose annotations
- Module organisation strategy (feature-based, layer-based, domain-driven)
- Monorepo vs multi-repo decision with rationale
- File naming conventions (kebab-case, camelCase, etc.)
- Configuration file locations (env, config, secrets)
- Shared code and utility organisation
- Entry point architecture (server, CLI, workers)
- README template for each major directory`
        },
        {
            area: 'dependencies',
            title: `Dependency Mapping: ${productName}`,
            description: `Dependency mapping for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- Internal module dependency graph (which modules depend on which)
- External library inventory with versions, licences, and maintenance status
- Version pinning strategy (exact, caret, tilde)
- Licence audit (MIT, Apache, GPL compatibility)
- Dependency update strategy (Dependabot, Renovate, manual)
- Bundle size analysis for frontend dependencies
- Security scanning approach (npm audit, Snyk, etc.)
- Lock file strategy (package-lock.json, pnpm-lock.yaml)`
        },
        {
            area: 'infrastructure',
            title: `Infrastructure Design: ${productName}`,
            description: `Infrastructure design for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- Hosting platform recommendation (Cloudflare, AWS, Vercel, Railway, etc.)
- Compute requirements (serverless, containers, VMs) with rationale
- Storage architecture (database hosting, file storage, CDN)
- Networking design (DNS, load balancing, SSL/TLS)
- Environment strategy (development, staging, production)
- Scaling approach (horizontal, vertical, auto-scaling triggers)
- Cost estimates per environment (monthly projected costs)
- Disaster recovery and backup strategy`
        },
        {
            area: 'cicd',
            title: `CI/CD Pipeline: ${productName}`,
            description: `CI/CD pipeline design for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- Pipeline stages (lint → build → test → deploy) with tools for each
- Build configuration (bundler, transpiler, optimisation)
- Test automation strategy (unit, integration, E2E in pipeline)
- Deployment strategy (blue-green, canary, rolling, or direct)
- Branch strategy (trunk-based, GitFlow, GitHub Flow)
- Environment promotion flow (dev → staging → production)
- Rollback procedure
- Pipeline configuration file template (GitHub Actions, GitLab CI, etc.)`
        },
        {
            area: 'security',
            title: `Security Architecture: ${productName}`,
            description: `Security architecture for ${productName}. Seed idea: ${seed}${ctx}

Deliverables:
- Authentication mechanism (JWT, session, OAuth2, passkeys) with rationale
- Authorisation model (RBAC, ABAC, ACL) with role definitions
- Data encryption strategy (at rest, in transit, field-level)
- Secrets management approach (env vars, vault, cloud KMS)
- Input validation and sanitisation strategy
- OWASP Top 10 mitigation checklist
- Rate limiting and abuse prevention
- Security headers and CSP configuration
- Audit logging requirements`
        }
    ];
}

// ── getBuildSubagents ────────────────────────────────────

/**
 * Get parallel build subagents for the build phase.
 * Returns 6 focused construction prompts covering scaffold, backend, frontend, integration, tooling, and docs.
 */
export function getBuildSubagents(productName: string, seed: string, knowledgeSummary: string) {
    const ctx = knowledgeSummary ? `\n\nAccumulated knowledge from research, design, and architecture phases:\n${knowledgeSummary}` : '';

    return [
        {
            area: 'scaffold',
            title: `Project Scaffold — ${productName}`,
            description: `You are a project scaffolding specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create the project directory structure and foundational files per the architecture specification.

Deliver:
- Directory structure matching the architecture spec (src/, tests/, config/, docs/, etc.)
- Package manifest (package.json, requirements.txt, Cargo.toml, etc.) with all dependencies and versions from the architecture spec
- Configuration files (tsconfig, eslint, prettier, .env.example, .gitignore)
- Build tool configuration (webpack, vite, esbuild, Makefile, etc.)
- Initial entry points (main.js/ts, index.html, etc.) with minimal boilerplate
- Database migration scripts or schema files if specified in architecture
- Docker/container configuration files if specified

Tag findings with [KNOWLEDGE category="scaffold" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'backend',
            title: `Backend Implementation — ${productName}`,
            description: `You are a backend implementation specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Implement the server-side code per the design and architecture specifications.

Deliver:
- Server setup and configuration (Express, FastAPI, Actix, etc.)
- API endpoint implementations matching the design spec (routes, controllers, handlers)
- Database models, schemas, and migration scripts per the data model design
- Authentication and authorisation middleware per the security architecture
- Business logic implementation for core features
- Input validation and error handling
- Database connection and query layer
- Middleware chain (logging, CORS, rate limiting, etc.)

Tag findings with [KNOWLEDGE category="backend" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'frontend',
            title: `Frontend Implementation — ${productName}`,
            description: `You are a frontend implementation specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Implement the user interface per the UX wireframes, interaction flows, and design specifications.

Deliver:
- Page/view components matching the page inventory from design
- Component hierarchy per the design spec (atomic design or equivalent)
- Routing and navigation implementation
- State management setup and store definitions
- Form implementations with validation per the interaction design
- Responsive layouts matching the responsive strategy
- Design system tokens (colours, typography, spacing) per the design spec
- Loading, empty, and error states per the interaction design
- Accessibility implementation (ARIA attributes, keyboard navigation, focus management)

Tag findings with [KNOWLEDGE category="frontend" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'integration',
            title: `Integration Wiring — ${productName}`,
            description: `You are an integration specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Wire together frontend and backend, implement data flow, and ensure end-to-end functionality.

Deliver:
- API client/service layer connecting frontend to backend endpoints
- Data fetching hooks/utilities (React Query, SWR, fetch wrappers, etc.)
- Request/response type definitions matching API spec
- Error handling and retry logic for network failures
- Loading state management during API calls
- Real-time update wiring (WebSocket, SSE) if specified in design
- Authentication flow integration (login, token refresh, logout)
- Environment-based API URL configuration
- End-to-end data flow verification for critical user paths

Tag findings with [KNOWLEDGE category="integration" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'tooling',
            title: `Tooling & DevOps — ${productName}`,
            description: `You are a tooling and DevOps specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Set up development tooling, testing framework, build scripts, and CI/CD configuration per the architecture spec.

Deliver:
- Linting configuration (ESLint, Pylint, Clippy, etc.) with project-appropriate rules
- Code formatting (Prettier, Black, rustfmt) with configuration
- Testing framework setup (Jest, Pytest, Cargo test) with example tests
- Build scripts for development and production
- CI/CD pipeline configuration (GitHub Actions, GitLab CI) per the CI/CD architecture
- Environment configuration (.env handling, config modules)
- Docker/container build files (Dockerfile, docker-compose.yml) if specified
- Git hooks (pre-commit, pre-push) for code quality
- Development server with hot reload configuration

Tag findings with [KNOWLEDGE category="tooling" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'docs',
            title: `Inline Documentation — ${productName}`,
            description: `You are a documentation specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create project documentation and inline code documentation for the built codebase.

Deliver:
- README.md with project overview, setup instructions, usage examples, and architecture summary
- API documentation (endpoint reference, request/response examples, authentication guide)
- Deployment guide (environment setup, configuration, build steps, hosting)
- CLAUDE.md with project conventions, structure, and development workflow
- CONTRIBUTING.md with code style, PR process, testing requirements
- Inline code comments for complex business logic and non-obvious algorithms
- Environment variable documentation (.env.example with descriptions)
- Architecture decision records for key technical choices made during build

Tag findings with [KNOWLEDGE category="docs" title="..."]...[/KNOWLEDGE]`
        }
    ];
}

// ── getTestSubagents ─────────────────────────────────────

/**
 * Get parallel test subagents for the test phase.
 * Returns 6 focused testing prompts covering unit, integration, e2e, lint, security, and performance.
 */
export function getTestSubagents(productName: string, seed: string, knowledgeSummary: string) {
    const ctx = knowledgeSummary ? `\n\nAccumulated knowledge from research, design, architecture, and build phases:\n${knowledgeSummary}` : '';

    return [
        {
            area: 'unit',
            title: `Unit Tests — ${productName}`,
            description: `You are a unit testing specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Write and run comprehensive unit tests for individual functions, classes, and modules.

Deliver:
- Unit tests for all core business logic functions and methods
- Edge case coverage: null inputs, empty arrays, boundary values, type coercion
- Error handling tests: verify exceptions are thrown correctly, error messages are accurate
- Mock/stub external dependencies (database, API calls, file system)
- Test data factories or fixtures for consistent test setup
- Coverage report identifying untested code paths
- Aim for >80% line coverage on business logic modules

Tag findings with [KNOWLEDGE category="unit" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'integration',
            title: `Integration Tests — ${productName}`,
            description: `You are an integration testing specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Write integration tests verifying that components work together correctly.

Deliver:
- API endpoint tests: HTTP method, route, request body, response status, response body
- Database integration: verify CRUD operations, migrations, constraints, transactions
- Middleware chain tests: authentication, authorisation, validation, error handling pipeline
- Service layer tests: verify business logic orchestration across multiple modules
- External service integration: mock external APIs, verify retry logic, timeout handling
- Authentication flow tests: login, token refresh, permission checks, session management
- Test database setup/teardown scripts for isolated test environments

Tag findings with [KNOWLEDGE category="integration" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'e2e',
            title: `End-to-End Tests — ${productName}`,
            description: `You are an end-to-end testing specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Write E2E tests covering critical user journeys through the full application stack.

Deliver:
- Critical path tests: user registration, login, core feature usage, logout
- Form submission flows: validation feedback, success states, error recovery
- Navigation tests: routing, deep links, back/forward, breadcrumbs
- Data persistence: verify data survives page refreshes, session changes
- Multi-step workflows: complete business processes end-to-end
- Cross-browser/device considerations documented
- Test environment configuration (headless browser setup, test URLs, seed data)
- Smoke test suite for quick deployment verification

Tag findings with [KNOWLEDGE category="e2e" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'lint',
            title: `Lint & Type Checks — ${productName}`,
            description: `You are a code quality specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Run linting, type checking, and formatting verification across the entire codebase.

Deliver:
- Linting results (ESLint, Pylint, Clippy, etc.) with violation counts by severity
- Type checking results (TypeScript strict mode, mypy, etc.) with error details
- Code formatting verification (Prettier, Black, rustfmt) — list non-conforming files
- Unused import/variable detection
- Complexity metrics: cyclomatic complexity, function length, file size warnings
- Naming convention violations (camelCase, snake_case consistency)
- Fix recommendations prioritised by severity (error → warning → info)
- Summary: total violations, files affected, estimated fix effort

Tag findings with [KNOWLEDGE category="lint" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'security',
            title: `Security Audit — ${productName}`,
            description: `You are a security audit specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Perform a comprehensive security audit of the codebase.

Deliver:
- OWASP Top 10 checklist: injection, broken auth, sensitive data exposure, XXE, broken access control, misconfiguration, XSS, insecure deserialisation, known vulnerabilities, insufficient logging
- Dependency vulnerability scan: check for known CVEs in all dependencies
- Secrets detection: scan for hardcoded API keys, passwords, tokens, connection strings
- Input validation audit: identify all user input points, verify sanitisation
- Authentication/authorisation review: token handling, session management, permission checks
- CORS and CSP configuration review
- SQL injection / NoSQL injection risk assessment
- File upload security (if applicable): type validation, size limits, storage location
- Severity-rated findings: Critical, High, Medium, Low, Informational

Tag findings with [KNOWLEDGE category="security" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'performance',
            title: `Performance Tests — ${productName}`,
            description: `You are a performance testing specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Evaluate application performance and identify optimisation opportunities.

Deliver:
- Response time benchmarks for key API endpoints (p50, p95, p99)
- Database query analysis: identify slow queries, missing indices, N+1 problems
- Bundle size analysis (frontend): total size, largest modules, tree-shaking opportunities
- Memory usage profiling: identify leaks, excessive allocations, cache effectiveness
- Startup time measurement: application boot, database connection, initial data load
- Load testing recommendations: expected concurrent users, bottleneck predictions
- Caching assessment: what should be cached, TTL recommendations, invalidation strategy
- Asset optimisation: image compression, minification, lazy loading opportunities
- Performance budget recommendations with specific thresholds

Tag findings with [KNOWLEDGE category="performance" title="..."]...[/KNOWLEDGE]`
        }
    ];
}

// ── getDocumentSubagents ─────────────────────────────────

/**
 * Get parallel document subagents for the document phase.
 * Returns 6 focused documentation prompts covering readme, api, deployment, claude, adr, and userguide.
 */
export function getDocumentSubagents(productName: string, seed: string, knowledgeSummary: string) {
    const ctx = knowledgeSummary ? `\n\nAccumulated knowledge from all prior phases:\n${knowledgeSummary}` : '';

    return [
        {
            area: 'readme',
            title: `README & Contributing — ${productName}`,
            description: `You are a README and contributing guide specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create comprehensive README.md and CONTRIBUTING.md files for the project.

Deliver:
- README.md with:
  - Project name, badge placeholders, one-line description
  - Features list with brief descriptions
  - Prerequisites and installation instructions (step-by-step)
  - Quick start guide (get running in under 2 minutes)
  - Usage examples with code snippets for common operations
  - Configuration reference (environment variables, config files)
  - Project structure overview
  - Licence section
- CONTRIBUTING.md with:
  - Development environment setup
  - Code style and conventions
  - Branch naming and PR process
  - Testing requirements before submitting
  - Issue reporting guidelines

Tag findings with [KNOWLEDGE category="readme" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'api',
            title: `API Documentation — ${productName}`,
            description: `You are an API documentation specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create comprehensive API documentation for all endpoints and interfaces.

Deliver:
- Endpoint reference: HTTP method, path, description, parameters, request body schema, response schema, status codes
- Request/response examples (curl commands and JSON payloads) for every endpoint
- Authentication guide: how to obtain tokens, header format, token refresh flow
- Error code reference: all error codes with descriptions and resolution steps
- Rate limiting documentation: limits, headers, retry strategies
- Versioning strategy documentation
- OpenAPI/Swagger specification file if applicable
- WebSocket/real-time API documentation if applicable
- Pagination patterns and query parameter conventions

Tag findings with [KNOWLEDGE category="api" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'deployment',
            title: `Deployment Guide — ${productName}`,
            description: `You are a deployment documentation specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create a comprehensive deployment guide covering all environments.

Deliver:
- Environment setup: development, staging, production configurations
- Environment variables reference with descriptions, defaults, and required/optional status
- Build steps: development build, production build, asset compilation
- Hosting/infrastructure setup: server requirements, cloud provider instructions
- Database setup: migrations, seed data, backup/restore procedures
- SSL/TLS configuration
- Scaling considerations: horizontal scaling, load balancing, caching layers
- Monitoring and logging setup: health checks, log aggregation, alerting
- Troubleshooting guide: common issues, error messages, diagnostic steps
- Rollback procedures: how to revert to a previous version safely

Tag findings with [KNOWLEDGE category="deployment" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'claude',
            title: `CLAUDE.md & AI Context — ${productName}`,
            description: `You are an AI collaboration context specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create CLAUDE.md and supporting context files for future AI-assisted development.

Deliver:
- CLAUDE.md with:
  - Project overview and purpose (2-3 sentences)
  - Key commands (build, test, start, deploy)
  - Project structure with file/directory descriptions
  - Architecture summary (components, data flow, key patterns)
  - Conventions (naming, code style, commit messages, British/American English)
  - Current status and recent changes
  - Infrastructure details (ports, services, dependencies)
- claude-context/ folder contents:
  - CURRENT_STATUS.md — progress tracking template
  - ARCHITECTURE.md — system design document
  - DECISIONS.md — decision log template
- Development workflow documentation for AI pair programming

Tag findings with [KNOWLEDGE category="claude" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'adr',
            title: `Architecture Decision Records — ${productName}`,
            description: `You are an architecture decision records specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Document all key technical decisions made during the design, architecture, and build phases.

Deliver:
- ADR for each major technical decision:
  - Title (ADR-001: Choose X for Y)
  - Status (Accepted/Proposed/Deprecated)
  - Context: what prompted this decision
  - Decision: what was chosen
  - Alternatives considered with pros/cons
  - Consequences: what this decision means going forward
- Cover decisions including:
  - Language/framework selection
  - Database choice
  - Authentication mechanism
  - API design patterns
  - Hosting/infrastructure platform
  - Testing strategy
  - State management approach
- ADR index/table of contents

Tag findings with [KNOWLEDGE category="adr" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'userguide',
            title: `User Guide — ${productName}`,
            description: `You are a user guide specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create a comprehensive user-facing guide for the product.

Deliver:
- Getting started walkthrough: first-time user experience, account setup, initial configuration
- Feature walkthrough: each major feature with step-by-step instructions
- Screenshots/mockup descriptions: describe what each key screen looks like and its purpose
- Common workflows: step-by-step guides for typical user tasks
- FAQ: anticipated questions with clear answers
- Tips and tricks: power user features, keyboard shortcuts, time-saving techniques
- Accessibility features: screen reader support, keyboard navigation, high contrast options
- Troubleshooting: common user-facing issues and self-service solutions
- Glossary: product-specific terminology definitions

Tag findings with [KNOWLEDGE category="userguide" title="..."]...[/KNOWLEDGE]`
        }
    ];
}

// ── getDeploySubagents ───────────────────────────────────

/**
 * Get parallel deploy subagents for the deploy phase.
 * Returns 6 focused deployment prompts covering container, cicd, infrastructure, security, monitoring, and rollback.
 */
export function getDeploySubagents(productName: string, seed: string, knowledgeSummary: string) {
    const ctx = knowledgeSummary ? `\n\nAccumulated knowledge from all prior phases:\n${knowledgeSummary}` : '';

    return [
        {
            area: 'container',
            title: `Containerisation — ${productName}`,
            description: `You are a containerisation specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create Docker containerisation configuration for the project.

Deliver:
- Dockerfile with multi-stage build (build stage + production stage) for minimal image size
- docker-compose.yml for local development (app + database + any supporting services)
- docker-compose.prod.yml for production deployment
- .dockerignore file excluding node_modules, .git, tests, docs
- Container health check endpoint integration
- Environment-specific configuration (dev, staging, production) via environment variables
- Container registry setup instructions (Docker Hub, GitHub Container Registry, or ECR)
- Image tagging strategy (semantic versioning, git SHA, latest)
- Volume mounts for persistent data (database, uploads, logs)
- Container resource limits and recommendations (CPU, memory)

Tag findings with [KNOWLEDGE category="container" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'cicd',
            title: `CI/CD Pipeline — ${productName}`,
            description: `You are a CI/CD pipeline specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Create CI/CD pipeline configuration for automated build, test, and deployment.

Deliver:
- GitHub Actions workflow files (or GitLab CI equivalent):
  - CI pipeline: lint, type check, unit tests, integration tests on every push/PR
  - CD pipeline: build, tag, push container image, deploy to staging/production
- Branch strategy: main (production), staging, feature branches with PR requirements
- Automated testing gates: PRs must pass all checks before merge
- Deployment triggers: auto-deploy to staging on merge to main, manual approval for production
- Artefact management: build outputs, test reports, coverage reports
- Environment secrets management in CI/CD (GitHub Secrets, environment variables)
- Cache strategies for faster builds (dependency caching, Docker layer caching)
- Notification integration: Slack/email on build failures, deployment success
- Rollback trigger: manual workflow dispatch for emergency rollbacks

Tag findings with [KNOWLEDGE category="cicd" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'infrastructure',
            title: `Infrastructure Provisioning — ${productName}`,
            description: `You are an infrastructure provisioning specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Define and provision the hosting infrastructure for the project.

Deliver:
- Hosting platform setup per architecture spec (Cloudflare Workers, Vercel, AWS, DigitalOcean, etc.)
- Compute configuration: instance type/tier, auto-scaling rules, region selection
- Database provisioning: managed database setup, connection pooling, read replicas if needed
- Storage configuration: object storage (S3/R2) for assets, CDN distribution
- Networking: load balancer, reverse proxy (nginx/Caddy), domain routing
- DNS configuration: domain setup, A/CNAME records, subdomain routing
- Environment variable management: production secrets, configuration injection
- CDN configuration: edge caching, cache invalidation strategy
- Cost estimation: monthly infrastructure cost breakdown by service
- Infrastructure as Code templates (Terraform, Pulumi, or platform-specific) if applicable

Tag findings with [KNOWLEDGE category="infrastructure" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'security',
            title: `Security & SSL — ${productName}`,
            description: `You are a deployment security specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Configure SSL/TLS and harden the production deployment security.

Deliver:
- SSL/TLS certificate provisioning: Let's Encrypt, Cloudflare, or managed certificates
- HTTPS enforcement: HTTP → HTTPS redirect, HSTS header configuration
- Security headers: Content-Security-Policy, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy
- Secrets management: production secrets storage (environment variables, vault, sealed secrets)
- Firewall rules: allowed ports, IP allowlisting if applicable, DDoS protection
- Access control: SSH key management, deployment credentials, least-privilege IAM roles
- Container security: non-root user, read-only filesystem where possible, security scanning
- Rate limiting configuration for production traffic
- CORS configuration for production domains
- Security audit checklist for pre-deployment verification

Tag findings with [KNOWLEDGE category="security" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'monitoring',
            title: `Monitoring & Health — ${productName}`,
            description: `You are a monitoring and observability specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Set up monitoring, health checks, and observability for the production deployment.

Deliver:
- Health check endpoints: /health (basic), /health/ready (dependencies), /health/live (liveness)
- Uptime monitoring: external monitoring service configuration (UptimeRobot, Pingdom, or similar)
- Application metrics: request rate, error rate, response latency (p50/p95/p99), active connections
- Log aggregation: structured logging format, log shipping configuration, log retention policy
- Alerting rules: downtime alerts, error rate thresholds, latency degradation, disk/memory warnings
- Dashboard configuration: key metrics visualisation (Grafana, Datadog, or platform-native)
- Performance baselines: expected response times, throughput, resource utilisation
- Error tracking: exception monitoring integration (Sentry, Bugsnag, or similar)
- Status page setup: public status page for users showing service health
- On-call rotation recommendations and escalation paths

Tag findings with [KNOWLEDGE category="monitoring" title="..."]...[/KNOWLEDGE]`
        },
        {
            area: 'rollback',
            title: `Rollback & Recovery — ${productName}`,
            description: `You are a disaster recovery specialist for "${productName}". Seed idea: ${seed}${ctx}

Your task: Define rollback procedures, backup strategy, and disaster recovery plan.

Deliver:
- Deployment strategy: blue-green, canary, or rolling update with specific configuration
- Rollback procedures: step-by-step guide for reverting to previous version within minutes
- Database backup strategy: automated backups, backup frequency, retention period, storage location
- Database migration rollback: reverse migration scripts, data recovery procedures
- Asset backup: user uploads, configuration files, static assets
- Disaster recovery runbook: complete recovery procedure from total infrastructure failure
- RTO (Recovery Time Objective) and RPO (Recovery Point Objective) targets with justification
- Failover testing plan: scheduled chaos engineering or failover drill procedures
- Incident response procedures: detection, triage, communication, resolution, post-mortem
- Data export/portability: how to extract all data for migration or compliance

Tag findings with [KNOWLEDGE category="rollback" title="..."]...[/KNOWLEDGE]`
        }
    ];
}

// ── executePhase ─────────────────────────────────────────

/**
 * Execute a specific phase for a product by creating a goal.
 */
export function executePhase(productId: string, phase: string) {
    const product = productStmts.get.get(productId) as any;
    if (!product) return null;

    const now = new Date().toISOString();

    // Research phase: spawn parallel subagent swarm
    if (phase === 'research') {
        try {
            const parentDesc = `Research phase for ${product.name} — orchestrate parallel research subagents and synthesise findings. Seed: ${product.seed}`;
            const parentGoalId = createGoal(parentDesc, product.project_path, false, null, 'parent');

            const areas = getResearchSubagents(product.name, product.seed);
            const childGoalIds: string[] = [];

            for (const area of areas) {
                const childGoalId = createGoal(area.description, product.project_path, true, parentGoalId, 'child', 'sonnet');
                childGoalIds.push(childGoalId);
                console.log(`[Pipeline] Research subagent created: ${area.area} (${childGoalId})`);
            }

            phaseStmts.updateStatus.run('active', now, productId, phase);
            phaseStmts.updateGoal.run(parentGoalId, productId, phase);
            productStmts.updatePhase.run(phase, PIPELINE_PHASES.indexOf(phase), productId);

            if (broadcast) {
                broadcast({ type: 'pipeline_phase_started', productId, phase, goalId: parentGoalId, childGoals: childGoalIds.length });
            }

            console.log(`[Pipeline] Research phase started for "${product.name}" — parent ${parentGoalId}, ${childGoalIds.length} children`);
            return parentGoalId;
        } catch (err: any) {
            console.error(`[Pipeline] Failed to execute research phase for ${product.name}:`, err.message);
            return null;
        }
    }

    // Design phase: spawn parallel design artifact swarm
    if (phase === 'design') {
        try {
            const knowledgeSummary = getKnowledgeSummary(productId);
            const parentDesc = `Design phase for ${product.name} — orchestrate parallel design subagents producing structured artifacts. Seed: ${product.seed}`;
            const parentGoalId = createGoal(parentDesc, product.project_path, false, null, 'parent');

            const areas = getDesignSubagents(product.name, product.seed, knowledgeSummary);
            const childGoalIds: string[] = [];

            for (const area of areas) {
                const childGoalId = createGoal(area.description, product.project_path, true, parentGoalId, 'child', 'sonnet');
                childGoalIds.push(childGoalId);
                console.log(`[Pipeline] Design subagent created: ${area.area} (${childGoalId})`);
            }

            phaseStmts.updateStatus.run('active', now, productId, phase);
            phaseStmts.updateGoal.run(parentGoalId, productId, phase);
            productStmts.updatePhase.run(phase, PIPELINE_PHASES.indexOf(phase), productId);

            if (broadcast) {
                broadcast({ type: 'pipeline_phase_started', productId, phase, goalId: parentGoalId, childGoals: childGoalIds.length });
            }

            console.log(`[Pipeline] Design phase started for "${product.name}" — parent ${parentGoalId}, ${childGoalIds.length} children`);
            return parentGoalId;
        } catch (err: any) {
            console.error(`[Pipeline] Failed to execute design phase for ${product.name}:`, err.message);
            return null;
        }
    }

    // Architecture phase: spawn parallel architecture swarm
    if (phase === 'architecture') {
        try {
            const knowledgeSummary = getKnowledgeSummary(productId);
            const parentDesc = `Architecture phase for ${product.name} — orchestrate parallel architecture subagents producing technical specifications. Seed: ${product.seed}`;
            const parentGoalId = createGoal(parentDesc, product.project_path, false, null, 'parent');

            const areas = getArchitectureSubagents(product.name, product.seed, knowledgeSummary);
            const childGoalIds: string[] = [];

            for (const area of areas) {
                const childGoalId = createGoal(area.description, product.project_path, true, parentGoalId, 'child', 'sonnet');
                childGoalIds.push(childGoalId);
                console.log(`[Pipeline] Architecture subagent created: ${area.area} (${childGoalId})`);
            }

            phaseStmts.updateStatus.run('active', now, productId, phase);
            phaseStmts.updateGoal.run(parentGoalId, productId, phase);
            productStmts.updatePhase.run(phase, PIPELINE_PHASES.indexOf(phase), productId);

            if (broadcast) {
                broadcast({ type: 'pipeline_phase_started', productId, phase, goalId: parentGoalId, childGoals: childGoalIds.length });
            }

            console.log(`[Pipeline] Architecture phase started for "${product.name}" — parent ${parentGoalId}, ${childGoalIds.length} children`);
            return parentGoalId;
        } catch (err: any) {
            console.error(`[Pipeline] Failed to execute architecture phase for ${product.name}:`, err.message);
            return null;
        }
    }

    // Build phase: spawn parallel build swarm
    if (phase === 'build') {
        try {
            const knowledgeSummary = getKnowledgeSummary(productId);
            const parentDesc = `Build phase for ${product.name} — orchestrate parallel build subagents constructing the product. Seed: ${product.seed}`;
            const parentGoalId = createGoal(parentDesc, product.project_path, false, null, 'parent');

            const areas = getBuildSubagents(product.name, product.seed, knowledgeSummary);
            const childGoalIds: string[] = [];

            for (const area of areas) {
                const childGoalId = createGoal(area.description, product.project_path, true, parentGoalId, 'child', 'sonnet');
                childGoalIds.push(childGoalId);
                console.log(`[Pipeline] Build subagent created: ${area.area} (${childGoalId})`);
            }

            phaseStmts.updateStatus.run('active', now, productId, phase);
            phaseStmts.updateGoal.run(parentGoalId, productId, phase);
            productStmts.updatePhase.run(phase, PIPELINE_PHASES.indexOf(phase), productId);

            if (broadcast) {
                broadcast({ type: 'pipeline_phase_started', productId, phase, goalId: parentGoalId, childGoals: childGoalIds.length });
            }

            console.log(`[Pipeline] Build phase started for "${product.name}" — parent ${parentGoalId}, ${childGoalIds.length} children`);
            return parentGoalId;
        } catch (err: any) {
            console.error(`[Pipeline] Failed to execute build phase for ${product.name}:`, err.message);
            return null;
        }
    }

    // Test phase: spawn parallel test swarm
    if (phase === 'test') {
        try {
            const knowledgeSummary = getKnowledgeSummary(productId);
            const parentDesc = `Test phase for ${product.name} — orchestrate parallel test subagents verifying quality across all dimensions. Seed: ${product.seed}`;
            const parentGoalId = createGoal(parentDesc, product.project_path, false, null, 'parent');

            const areas = getTestSubagents(product.name, product.seed, knowledgeSummary);
            const childGoalIds: string[] = [];

            for (const area of areas) {
                const childGoalId = createGoal(area.description, product.project_path, true, parentGoalId, 'child', 'sonnet');
                childGoalIds.push(childGoalId);
                console.log(`[Pipeline] Test subagent created: ${area.area} (${childGoalId})`);
            }

            phaseStmts.updateStatus.run('active', now, productId, phase);
            phaseStmts.updateGoal.run(parentGoalId, productId, phase);
            productStmts.updatePhase.run(phase, PIPELINE_PHASES.indexOf(phase), productId);

            if (broadcast) {
                broadcast({ type: 'pipeline_phase_started', productId, phase, goalId: parentGoalId, childGoals: childGoalIds.length });
            }

            console.log(`[Pipeline] Test phase started for "${product.name}" — parent ${parentGoalId}, ${childGoalIds.length} children`);
            return parentGoalId;
        } catch (err: any) {
            console.error(`[Pipeline] Failed to execute test phase for ${product.name}:`, err.message);
            return null;
        }
    }

    // Document phase: spawn parallel document swarm
    if (phase === 'document') {
        try {
            const knowledgeSummary = getKnowledgeSummary(productId);
            const parentDesc = `Document phase for ${product.name} — orchestrate parallel documentation subagents producing comprehensive project documentation. Seed: ${product.seed}`;
            const parentGoalId = createGoal(parentDesc, product.project_path, false, null, 'parent');

            const areas = getDocumentSubagents(product.name, product.seed, knowledgeSummary);
            const childGoalIds: string[] = [];

            for (const area of areas) {
                const childGoalId = createGoal(area.description, product.project_path, true, parentGoalId, 'child', 'sonnet');
                childGoalIds.push(childGoalId);
                console.log(`[Pipeline] Document subagent created: ${area.area} (${childGoalId})`);
            }

            phaseStmts.updateStatus.run('active', now, productId, phase);
            phaseStmts.updateGoal.run(parentGoalId, productId, phase);
            productStmts.updatePhase.run(phase, PIPELINE_PHASES.indexOf(phase), productId);

            if (broadcast) {
                broadcast({ type: 'pipeline_phase_started', productId, phase, goalId: parentGoalId, childGoals: childGoalIds.length });
            }

            console.log(`[Pipeline] Document phase started for "${product.name}" — parent ${parentGoalId}, ${childGoalIds.length} children`);
            return parentGoalId;
        } catch (err: any) {
            console.error(`[Pipeline] Failed to execute document phase for ${product.name}:`, err.message);
            return null;
        }
    }

    // Deploy phase: spawn parallel deploy swarm
    if (phase === 'deploy') {
        try {
            const knowledgeSummary = getKnowledgeSummary(productId);
            const parentDesc = `Deploy phase for ${product.name} — orchestrate parallel deploy subagents preparing production infrastructure and deployment. Seed: ${product.seed}`;
            const parentGoalId = createGoal(parentDesc, product.project_path, false, null, 'parent');

            const areas = getDeploySubagents(product.name, product.seed, knowledgeSummary);
            const childGoalIds: string[] = [];

            for (const area of areas) {
                const childGoalId = createGoal(area.description, product.project_path, true, parentGoalId, 'child', 'sonnet');
                childGoalIds.push(childGoalId);
                console.log(`[Pipeline] Deploy subagent created: ${area.area} (${childGoalId})`);
            }

            phaseStmts.updateStatus.run('active', now, productId, phase);
            phaseStmts.updateGoal.run(parentGoalId, productId, phase);
            productStmts.updatePhase.run(phase, PIPELINE_PHASES.indexOf(phase), productId);

            if (broadcast) {
                broadcast({ type: 'pipeline_phase_started', productId, phase, goalId: parentGoalId, childGoals: childGoalIds.length });
            }

            console.log(`[Pipeline] Deploy phase started for "${product.name}" — parent ${parentGoalId}, ${childGoalIds.length} children`);
            return parentGoalId;
        } catch (err: any) {
            console.error(`[Pipeline] Failed to execute deploy phase for ${product.name}:`, err.message);
            return null;
        }
    }

    // Fallback for any unexpected phase
    console.error(`[Pipeline] Unknown phase "${phase}" for ${product.name}`);
    return null;
}

// ── advancePipeline ──────────────────────────────────────

/**
 * Advance the product pipeline after a phase completes.
 * Called from updateGoalProgress() when a goal linked to a product phase completes.
 */
export function advancePipeline(productId: string, completedPhase: string, goalResult?: any) {
    const product = productStmts.get.get(productId) as any;
    if (!product) return;

    const now = new Date().toISOString();

    // Mark phase as completed
    const goal = goalResult || {};
    phaseStmts.complete.run('completed', now, goal.cost_usd || 0, JSON.stringify(goal.artifacts || []), productId, completedPhase);

    // Update product cost
    const phases = phaseStmts.getByProduct.all(productId) as any[];
    const totalCost = phases.reduce((sum: number, p: any) => sum + (p.cost_usd || 0), 0);
    productStmts.updateCost.run(totalCost, productId);

    // Extract knowledge from goal results
    if (goal.result_summary || goal.description) {
        try {
            knowledgeStmts.insert.run(
                productId, completedPhase,
                `${completedPhase} phase results`,
                goal.result_summary || `Completed: ${goal.description || completedPhase}`,
                completedPhase, now
            );
        } catch (err: any) {
            console.error(`[Pipeline] Failed to store knowledge:`, err.message);
        }
    }

    // Find next phase
    const currentIndex = PIPELINE_PHASES.indexOf(completedPhase);
    if (currentIndex >= PIPELINE_PHASES.length - 1) {
        // All phases complete
        productStmts.updateStatus.run('completed', now, productId);
        if (broadcast) {
            broadcast({ type: 'pipeline_completed', productId, name: product.name });
        }
        const config = loadConfig();
        if (config.ntfy_topic) {
            try {
                execFileSync('curl', ['-s', '-d', `Product "${product.name}" pipeline completed!`, '-H', 'Title: Pipeline Complete', '-H', 'Priority: high', '-H', 'Tags: rocket', `https://ntfy.sh/${config.ntfy_topic}`], { timeout: 10000, stdio: 'ignore' });
            } catch {}
        }
        console.log(`[Pipeline] Product "${product.name}" completed all phases`);
        return;
    }

    const nextPhase = PIPELINE_PHASES[currentIndex + 1];

    if (GATED_PHASES.includes(nextPhase)) {
        // Gate: wait for approval
        phaseStmts.updateGate.run('pending', null, null, productId, nextPhase);
        if (broadcast) {
            broadcast({ type: 'pipeline_gate_pending', productId, name: product.name, phase: nextPhase, completedPhase });
        }
        const config = loadConfig();
        if (config.ntfy_topic) {
            try {
                execFileSync('curl', ['-s', '-d', `Phase "${completedPhase}" complete for ${product.name}. Approve "${nextPhase}" to continue.`, '-H', 'Title: Pipeline Gate', '-H', 'Priority: default', '-H', 'Tags: traffic_light', `https://ntfy.sh/${config.ntfy_topic}`], { timeout: 10000, stdio: 'ignore' });
            } catch {}
        }
        console.log(`[Pipeline] Gate pending for "${nextPhase}" on "${product.name}"`);
    } else {
        // No gate — auto-advance
        executePhase(productId, nextPhase);
    }
}

// ── synthesizeResearchFindings ────────────────────────────

/**
 * Synthesise research findings from all child research goals into a Research Brief.
 * Stores as a knowledge entry with category='research_brief'.
 */
export function synthesizeResearchFindings(parentGoalId: string) {
    try {
        const phase = (db as any).prepare('SELECT product_id FROM product_phases WHERE goal_id = ?').get(parentGoalId);
        if (!phase) return;

        const productId = phase.product_id;
        const product = productStmts.get.get(productId) as any;
        if (!product) return;

        const children = goalStmts.getChildren.all(parentGoalId) as any[];
        const allKnowledge = (knowledgeStmts.getByProduct.all(productId) as any[]).filter(k => k.source_phase === 'research' && k.category !== 'research_brief');

        let brief = `# Research Brief: ${product.name}\n\n`;
        brief += `**Seed Idea:** ${product.seed}\n\n`;
        brief += `**Completed:** ${new Date().toISOString().split('T')[0]}\n\n---\n\n`;

        // Group knowledge by category
        const byCategory: Record<string, any[]> = {};
        for (const k of allKnowledge) {
            if (!byCategory[k.category]) byCategory[k.category] = [];
            byCategory[k.category].push(k);
        }

        const categoryNames: Record<string, string> = {
            market: 'Market Research', technical: 'Technical Feasibility',
            competitive: 'Competitive Analysis', practices: 'Engineering Best Practices',
            regulatory: 'Regulatory & Compliance', ux: 'UX Patterns & Design'
        };

        for (const [category, entries] of Object.entries(byCategory)) {
            brief += `## ${categoryNames[category] || category}\n\n`;
            for (const entry of entries) {
                brief += `### ${entry.title}\n\n${entry.content}\n\n`;
            }
        }

        // Execution summary
        brief += `---\n\n## Execution Summary\n\n`;
        for (const child of children) {
            const area = child.description.split('.')[0].slice(0, 60);
            brief += `- **${area}**: ${child.status} (${child.tasks_completed || 0}/${child.task_count || 0} tasks, $${(child.total_cost_usd || 0).toFixed(4)})\n`;
        }
        const totalCost = children.reduce((sum: number, c: any) => sum + (c.total_cost_usd || 0), 0);
        brief += `\n**Total Research Cost:** $${totalCost.toFixed(4)}\n`;

        const now = new Date().toISOString();
        knowledgeStmts.insert.run(productId, 'research_brief', `Complete Research Brief — ${product.name}`, brief, 'research', now);

        console.log(`[Pipeline] Research synthesis complete for "${product.name}" — ${allKnowledge.length} findings, $${totalCost.toFixed(4)}`);
    } catch (err: any) {
        console.error(`[Pipeline] Research synthesis failed for parent ${parentGoalId}:`, err.message);
    }
}

// ── synthesizeDesignArtifacts ────────────────────────────

/**
 * Synthesise design artifacts from all child design goals into a Design Package.
 * Stores as a knowledge entry with category='design_package'.
 */
export function synthesizeDesignArtifacts(parentGoalId: string) {
    try {
        const phaseRecord = (db as any).prepare('SELECT product_id FROM product_phases WHERE goal_id = ?').get(parentGoalId);
        if (!phaseRecord) return;

        const productId = phaseRecord.product_id;
        const product = productStmts.get.get(productId) as any;
        if (!product) return;

        const children = goalStmts.getChildren.all(parentGoalId) as any[];
        const allKnowledge = (knowledgeStmts.getByProduct.all(productId) as any[]).filter(k => k.source_phase === 'design' && k.category !== 'design_package');

        let pkg = `# Design Package: ${product.name}\n\n`;
        pkg += `**Seed Idea:** ${product.seed}\n\n`;
        pkg += `**Completed:** ${new Date().toISOString().split('T')[0]}\n\n---\n\n`;

        const byCategory: Record<string, any[]> = {};
        for (const k of allKnowledge) {
            if (!byCategory[k.category]) byCategory[k.category] = [];
            byCategory[k.category].push(k);
        }

        const categoryNames: Record<string, string> = {
            requirements: 'Requirements Specification', datamodel: 'Data Model',
            api: 'API Specification', ux: 'UX & Wireframes',
            interactions: 'Interaction Design', accessibility: 'Accessibility'
        };

        for (const [category, entries] of Object.entries(byCategory)) {
            pkg += `## ${categoryNames[category] || category}\n\n`;
            for (const entry of entries) {
                pkg += `### ${entry.title}\n\n${entry.content}\n\n`;
            }
        }

        pkg += `---\n\n## Execution Summary\n\n`;
        for (const child of children) {
            const area = child.description.split('.')[0].slice(0, 60);
            pkg += `- **${area}**: ${child.status} (${child.tasks_completed || 0}/${child.task_count || 0} tasks, $${(child.total_cost_usd || 0).toFixed(4)})\n`;
        }
        const totalCost = children.reduce((sum: number, c: any) => sum + (c.total_cost_usd || 0), 0);
        pkg += `\n**Total Design Cost:** $${totalCost.toFixed(4)}\n`;

        const now = new Date().toISOString();
        knowledgeStmts.insert.run(productId, 'design_package', `Complete Design Package — ${product.name}`, pkg, 'design', now);

        console.log(`[Pipeline] Design synthesis complete for "${product.name}" — ${allKnowledge.length} artifacts, $${totalCost.toFixed(4)}`);
    } catch (err: any) {
        console.error(`[Pipeline] Design synthesis failed for parent ${parentGoalId}:`, err.message);
    }
}

// ── synthesizeArchitectureSpec ───────────────────────────

/**
 * Synthesise architecture decisions from all child architecture goals into an Architecture Specification.
 * Stores as a knowledge entry with category='architecture_spec'.
 */
export function synthesizeArchitectureSpec(parentGoalId: string) {
    try {
        const phaseRecord = (db as any).prepare('SELECT product_id FROM product_phases WHERE goal_id = ?').get(parentGoalId);
        if (!phaseRecord) return;

        const productId = phaseRecord.product_id;
        const product = productStmts.get.get(productId) as any;
        if (!product) return;

        const children = goalStmts.getChildren.all(parentGoalId) as any[];
        const allKnowledge = (knowledgeStmts.getByProduct.all(productId) as any[]).filter(k => k.source_phase === 'architecture' && k.category !== 'architecture_spec');

        let spec = `# Architecture Specification: ${product.name}\n\n`;
        spec += `**Seed Idea:** ${product.seed}\n\n`;
        spec += `**Completed:** ${new Date().toISOString().split('T')[0]}\n\n---\n\n`;

        const byCategory: Record<string, any[]> = {};
        for (const k of allKnowledge) {
            if (!byCategory[k.category]) byCategory[k.category] = [];
            byCategory[k.category].push(k);
        }

        const categoryNames: Record<string, string> = {
            stack: 'Technology Stack', structure: 'Project Structure',
            dependencies: 'Dependencies', infrastructure: 'Infrastructure',
            cicd: 'CI/CD Pipeline', security: 'Security Architecture'
        };

        for (const [category, entries] of Object.entries(byCategory)) {
            spec += `## ${categoryNames[category] || category}\n\n`;
            for (const entry of entries) {
                spec += `### ${entry.title}\n\n${entry.content}\n\n`;
            }
        }

        spec += `---\n\n## Execution Summary\n\n`;
        for (const child of children) {
            const area = child.description.split('.')[0].slice(0, 60);
            spec += `- **${area}**: ${child.status} (${child.tasks_completed || 0}/${child.task_count || 0} tasks, $${(child.total_cost_usd || 0).toFixed(4)})\n`;
        }
        const totalCost = children.reduce((sum: number, c: any) => sum + (c.total_cost_usd || 0), 0);
        spec += `\n**Total Architecture Cost:** $${totalCost.toFixed(4)}\n`;

        const now = new Date().toISOString();
        knowledgeStmts.insert.run(productId, 'architecture_spec', `Complete Architecture Specification — ${product.name}`, spec, 'architecture', now);

        console.log(`[Pipeline] Architecture synthesis complete for "${product.name}" — ${allKnowledge.length} decisions, $${totalCost.toFixed(4)}`);
    } catch (err: any) {
        console.error(`[Pipeline] Architecture synthesis failed for parent ${parentGoalId}:`, err.message);
    }
}

// ── synthesizeBuildResults ───────────────────────────────

/**
 * Synthesize build results from all build subagent knowledge into a Build Report.
 */
export function synthesizeBuildResults(parentGoalId: string) {
    try {
        const parent = goalStmts.get.get(parentGoalId) as any;
        if (!parent) return;

        const phaseRecord = (db as any).prepare('SELECT product_id FROM product_phases WHERE goal_id = ?').get(parentGoalId);
        if (!phaseRecord) return;

        const product = productStmts.get.get(phaseRecord.product_id) as any;
        if (!product) return;

        const allKnowledge = (knowledgeStmts.getByProduct.all(product.id) as any[])
            .filter(k => k.source_phase === 'build');

        const children = goalStmts.getChildren.all(parentGoalId) as any[];
        const totalCost = children.reduce((sum: number, c: any) => sum + (c.total_cost_usd || 0), 0);

        const categoryNames: Record<string, string> = {
            scaffold: 'Project Scaffold',
            backend: 'Backend',
            frontend: 'Frontend',
            integration: 'Integration',
            tooling: 'Tooling & DevOps',
            docs: 'Documentation'
        };

        const grouped: Record<string, any[]> = {};
        for (const k of allKnowledge) {
            if (k.category === 'build_report') continue;
            if (!grouped[k.category]) grouped[k.category] = [];
            grouped[k.category].push(k);
        }

        let report = `# Build Report — ${product.name}\n\n`;
        report += `> Generated ${new Date().toISOString()}\n\n`;

        for (const [cat, displayName] of Object.entries(categoryNames)) {
            report += `## ${displayName}\n\n`;
            if (grouped[cat] && grouped[cat].length > 0) {
                for (const k of grouped[cat]) {
                    report += `### ${k.title}\n\n${k.content}\n\n`;
                }
            } else {
                report += `*No knowledge entries recorded for this area.*\n\n`;
            }
        }

        // Include any uncategorised build knowledge
        for (const [cat, entries] of Object.entries(grouped)) {
            if (!categoryNames[cat]) {
                report += `## ${cat}\n\n`;
                for (const k of entries) {
                    report += `### ${k.title}\n\n${k.content}\n\n`;
                }
            }
        }

        report += `## Execution Summary\n\n`;
        report += `| Subagent | Status | Tasks | Cost |\n`;
        report += `|----------|--------|-------|------|\n`;
        for (const child of children) {
            const area = child.description.split('.')[0].split('\u2014')[0].trim();
            report += `| ${area} | ${child.status} | ${child.tasks_completed || 0}/${child.task_count || 0} | $${(child.total_cost_usd || 0).toFixed(4)} |\n`;
        }
        report += `\n**Total build cost:** $${totalCost.toFixed(4)}\n`;

        const now = new Date().toISOString();
        knowledgeStmts.insert.run(product.id, 'build_report', `Complete Build Report — ${product.name}`, report, 'build', now);

        console.log(`[Pipeline] Build synthesis complete for "${product.name}" — ${allKnowledge.length} entries, $${totalCost.toFixed(4)}`);
    } catch (err: any) {
        console.error(`[Pipeline] Build synthesis failed for parent ${parentGoalId}:`, err.message);
    }
}

// ── synthesizeTestResults ────────────────────────────────

/**
 * Synthesize test results from all test subagent knowledge into a Test Report.
 */
export function synthesizeTestResults(parentGoalId: string) {
    try {
        const parent = goalStmts.get.get(parentGoalId) as any;
        if (!parent) return;

        const phaseRecord = (db as any).prepare('SELECT product_id FROM product_phases WHERE goal_id = ?').get(parentGoalId);
        if (!phaseRecord) return;

        const product = productStmts.get.get(phaseRecord.product_id) as any;
        if (!product) return;

        const allKnowledge = (knowledgeStmts.getByProduct.all(product.id) as any[])
            .filter(k => k.source_phase === 'test');

        const children = goalStmts.getChildren.all(parentGoalId) as any[];
        const totalCost = children.reduce((sum: number, c: any) => sum + (c.total_cost_usd || 0), 0);

        const categoryNames: Record<string, string> = {
            unit: 'Unit Tests',
            integration: 'Integration Tests',
            e2e: 'End-to-End Tests',
            lint: 'Lint & Type Checks',
            security: 'Security Audit',
            performance: 'Performance Tests'
        };

        const grouped: Record<string, any[]> = {};
        for (const k of allKnowledge) {
            if (k.category === 'test_report') continue;
            if (!grouped[k.category]) grouped[k.category] = [];
            grouped[k.category].push(k);
        }

        let report = `# Test Report — ${product.name}\n\n`;
        report += `> Generated ${new Date().toISOString()}\n\n`;

        for (const [cat, displayName] of Object.entries(categoryNames)) {
            report += `## ${displayName}\n\n`;
            if (grouped[cat] && grouped[cat].length > 0) {
                for (const k of grouped[cat]) {
                    report += `### ${k.title}\n\n${k.content}\n\n`;
                }
            } else {
                report += `*No findings recorded for this area.*\n\n`;
            }
        }

        // Include any uncategorised test knowledge
        for (const [cat, entries] of Object.entries(grouped)) {
            if (!categoryNames[cat]) {
                report += `## ${cat}\n\n`;
                for (const k of entries) {
                    report += `### ${k.title}\n\n${k.content}\n\n`;
                }
            }
        }

        report += `## Execution Summary\n\n`;
        report += `| Subagent | Status | Tasks | Cost |\n`;
        report += `|----------|--------|-------|------|\n`;
        for (const child of children) {
            const area = child.description.split('.')[0].split('\u2014')[0].trim();
            report += `| ${area} | ${child.status} | ${child.tasks_completed || 0}/${child.task_count || 0} | $${(child.total_cost_usd || 0).toFixed(4)} |\n`;
        }
        report += `\n**Total test cost:** $${totalCost.toFixed(4)}\n`;

        const now = new Date().toISOString();
        knowledgeStmts.insert.run(product.id, 'test_report', `Complete Test Report — ${product.name}`, report, 'test', now);

        console.log(`[Pipeline] Test synthesis complete for "${product.name}" — ${allKnowledge.length} findings, $${totalCost.toFixed(4)}`);
    } catch (err: any) {
        console.error(`[Pipeline] Test synthesis failed for parent ${parentGoalId}:`, err.message);
    }
}

// ── synthesizeDocumentPackage ────────────────────────────

/**
 * Synthesize document results from all document subagent knowledge into a Documentation Package.
 */
export function synthesizeDocumentPackage(parentGoalId: string) {
    try {
        const parent = goalStmts.get.get(parentGoalId) as any;
        if (!parent) return;

        const phaseRecord = (db as any).prepare('SELECT product_id FROM product_phases WHERE goal_id = ?').get(parentGoalId);
        if (!phaseRecord) return;

        const product = productStmts.get.get(phaseRecord.product_id) as any;
        if (!product) return;

        const allKnowledge = (knowledgeStmts.getByProduct.all(product.id) as any[])
            .filter(k => k.source_phase === 'document');

        const children = goalStmts.getChildren.all(parentGoalId) as any[];
        const totalCost = children.reduce((sum: number, c: any) => sum + (c.total_cost_usd || 0), 0);

        const categoryNames: Record<string, string> = {
            readme: 'README & Contributing',
            api: 'API Documentation',
            deployment: 'Deployment Guide',
            claude: 'CLAUDE.md & AI Context',
            adr: 'Architecture Decision Records',
            userguide: 'User Guide'
        };

        const grouped: Record<string, any[]> = {};
        for (const k of allKnowledge) {
            if (k.category === 'document_package') continue;
            if (!grouped[k.category]) grouped[k.category] = [];
            grouped[k.category].push(k);
        }

        let report = `# Documentation Package — ${product.name}\n\n`;
        report += `> Generated ${new Date().toISOString()}\n\n`;

        for (const [cat, displayName] of Object.entries(categoryNames)) {
            report += `## ${displayName}\n\n`;
            if (grouped[cat] && grouped[cat].length > 0) {
                for (const k of grouped[cat]) {
                    report += `### ${k.title}\n\n${k.content}\n\n`;
                }
            } else {
                report += `*No documentation recorded for this area.*\n\n`;
            }
        }

        // Include any uncategorised document knowledge
        for (const [cat, entries] of Object.entries(grouped)) {
            if (!categoryNames[cat]) {
                report += `## ${cat}\n\n`;
                for (const k of entries) {
                    report += `### ${k.title}\n\n${k.content}\n\n`;
                }
            }
        }

        report += `## Execution Summary\n\n`;
        report += `| Subagent | Status | Tasks | Cost |\n`;
        report += `|----------|--------|-------|------|\n`;
        for (const child of children) {
            const area = child.description.split('.')[0].split('\u2014')[0].trim();
            report += `| ${area} | ${child.status} | ${child.tasks_completed || 0}/${child.task_count || 0} | $${(child.total_cost_usd || 0).toFixed(4)} |\n`;
        }
        report += `\n**Total documentation cost:** $${totalCost.toFixed(4)}\n`;

        const now = new Date().toISOString();
        knowledgeStmts.insert.run(product.id, 'document_package', `Complete Documentation Package — ${product.name}`, report, 'document', now);

        console.log(`[Pipeline] Document synthesis complete for "${product.name}" — ${allKnowledge.length} entries, $${totalCost.toFixed(4)}`);
    } catch (err: any) {
        console.error(`[Pipeline] Document synthesis failed for parent ${parentGoalId}:`, err.message);
    }
}

// ── synthesizeDeployReport ───────────────────────────────

/**
 * Synthesize deploy results from all deploy subagent knowledge into a Deploy Report.
 */
export function synthesizeDeployReport(parentGoalId: string) {
    try {
        const parent = goalStmts.get.get(parentGoalId) as any;
        if (!parent) return;

        const phaseRecord = (db as any).prepare('SELECT product_id FROM product_phases WHERE goal_id = ?').get(parentGoalId);
        if (!phaseRecord) return;

        const product = productStmts.get.get(phaseRecord.product_id) as any;
        if (!product) return;

        const allKnowledge = (knowledgeStmts.getByProduct.all(product.id) as any[])
            .filter(k => k.source_phase === 'deploy');

        const children = goalStmts.getChildren.all(parentGoalId) as any[];
        const totalCost = children.reduce((sum: number, c: any) => sum + (c.total_cost_usd || 0), 0);

        const categoryNames: Record<string, string> = {
            container: 'Containerisation',
            cicd: 'CI/CD Pipeline',
            infrastructure: 'Infrastructure',
            security: 'Security & SSL',
            monitoring: 'Monitoring & Health',
            rollback: 'Rollback & Recovery'
        };

        const grouped: Record<string, any[]> = {};
        for (const k of allKnowledge) {
            if (k.category === 'deploy_report') continue;
            if (!grouped[k.category]) grouped[k.category] = [];
            grouped[k.category].push(k);
        }

        let report = `# Deploy Report — ${product.name}\n\n`;
        report += `> Generated ${new Date().toISOString()}\n\n`;

        for (const [cat, displayName] of Object.entries(categoryNames)) {
            report += `## ${displayName}\n\n`;
            if (grouped[cat] && grouped[cat].length > 0) {
                for (const k of grouped[cat]) {
                    report += `### ${k.title}\n\n${k.content}\n\n`;
                }
            } else {
                report += `*No configuration recorded for this area.*\n\n`;
            }
        }

        // Include any uncategorised deploy knowledge
        for (const [cat, entries] of Object.entries(grouped)) {
            if (!categoryNames[cat]) {
                report += `## ${cat}\n\n`;
                for (const k of entries) {
                    report += `### ${k.title}\n\n${k.content}\n\n`;
                }
            }
        }

        report += `## Execution Summary\n\n`;
        report += `| Subagent | Status | Tasks | Cost |\n`;
        report += `|----------|--------|-------|------|\n`;
        for (const child of children) {
            const area = child.description.split('.')[0].split('\u2014')[0].trim();
            report += `| ${area} | ${child.status} | ${child.tasks_completed || 0}/${child.task_count || 0} | $${(child.total_cost_usd || 0).toFixed(4)} |\n`;
        }
        report += `\n**Total deploy cost:** $${totalCost.toFixed(4)}\n`;

        const now = new Date().toISOString();
        knowledgeStmts.insert.run(product.id, 'deploy_report', `Complete Deploy Report — ${product.name}`, report, 'deploy', now);

        console.log(`[Pipeline] Deploy synthesis complete for "${product.name}" — ${allKnowledge.length} entries, $${totalCost.toFixed(4)}`);
    } catch (err: any) {
        console.error(`[Pipeline] Deploy synthesis failed for parent ${parentGoalId}:`, err.message);
    }
}
