#!/bin/bash
# install-surface-units.sh — generate + install systemd user units for the T-2
# per-surface tmux sessions, derived from the Garden Manifest (no hand-lists).
#
# SUPERVISION MODEL (deliberate, single-manager — Jim's T-2 note #3):
#   - Units are Type=oneshot + RemainAfterExit=yes BOOT-LAUNCHERS only. NO Restart=.
#   - The ONE runtime manager of surface sessions is the tmux-dispatcher
#     (spawnAgentSession relaunches a missing session at dispatch time).
#   - Stopping a unit does NOT kill the tmux session (oneshot); killing sessions
#     is a human/dispatcher act. Exactly one manager per resource.
#
# Units are SYMLINKED into ~/.config/systemd/user (the S166 lesson: copied units
# go stale silently; only symlinks track the repo).
#
# Usage:
#   install-surface-units.sh                 # generate + install; enable NOTHING
#   install-surface-units.sh --enable leo    # also enable <slug>'s units at boot
#
# Per the agreed thaw sequence: Leo's units are enabled at his thaw; Jim's when
# his cycles thaw on Leo's passing data. Install-all/enable-explicitly keeps the
# stride launch-infrastructure-only (Jim's T-2 note #6).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
UNITS_DIR="$REPO_ROOT/systemd"
TARGET_DIR="$HOME/.config/systemd/user"

ENABLE_SLUG=""
if [[ "${1:-}" == "--enable" ]]; then ENABLE_SLUG="${2:?--enable needs a slug}"; fi

manifest_get() {
    (cd "$REPO_ROOT/src/server" && NODE_PATH="$(pwd)/node_modules" npx tsx ../../scripts/manifest-get.ts "$@")
}

mkdir -p "$UNITS_DIR" "$TARGET_DIR"

GENERATED=()
for SLUG in $(manifest_get agents); do
    for SURFACE in $(manifest_get surfaces "$SLUG"); do
        UNIT="han-surface-${SLUG}-${SURFACE}.service"
        cat > "$UNITS_DIR/$UNIT" << EOF
# GENERATED by scripts/install-surface-units.sh from the Garden Manifest — do not hand-edit.
# Boot-launcher ONLY (single-manager model: the tmux-dispatcher is the runtime
# manager; no Restart= here by design — see scripts/launch-tmux-surface.sh header).
[Unit]
Description=HAN ${SLUG}/${SURFACE} tmux surface session (serverless spoke)
After=default.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${SCRIPT_DIR}/launch-tmux-surface.sh ${SLUG} ${SURFACE}

[Install]
WantedBy=default.target
EOF
        ln -sf "$UNITS_DIR/$UNIT" "$TARGET_DIR/$UNIT"
        GENERATED+=("$UNIT")
        echo "generated + symlinked: $UNIT"
    done
done

systemctl --user daemon-reload

if [[ -n "$ENABLE_SLUG" ]]; then
    for UNIT in "${GENERATED[@]}"; do
        if [[ "$UNIT" == "han-surface-${ENABLE_SLUG}-"* ]]; then
            systemctl --user enable "$UNIT"
            echo "enabled at boot: $UNIT"
        fi
    done
else
    echo "no units enabled (pass --enable <slug> at the slug's thaw)"
fi
