#!/usr/bin/env tsx
/**
 * scripts/supersession-sweep.ts
 *
 * Plan v8 Step 7 — Mark pre-replay entries as supersession participants.
 *
 * After the replay engine has built fresh chains (Step 6), pre-existing
 * entries from the broken pipeline still sit in gradient_entries alongside
 * the new replay-built canonicals. This script marks them as supersession
 * participants so they:
 *   - Stay in the DB (memory is never deleted)
 *   - Have superseded_by pointing to the replay-built canonical at the
 *     same source-position (same c0_root + same level)
 *   - Get a revisit feeling tag generated by Opus 4.7 reading them briefly
 *     (per the supersession=revisit rule from Plan v7 addendum)
 *   - Get qualifier='pre-replay' so loadTraversableGradient can exclude
 *     them from the prompt while keeping them queryable
 *
 * Entries with broken provenance (NULL source_id or chain-broken) get
 * qualifier='broken-lineage' — no replay-built canonical to point at.
 *
 * Usage:
 *   npx tsx scripts/supersession-sweep.ts --agent=jim          # dry-run
 *   npx tsx scripts/supersession-sweep.ts --agent=jim --apply  # apply
 *
 * Sovereignty: --agent flag scopes all writes to that agent's rows only.
 *
 * MUST run AFTER the replay engine has completed for the agent. If run
 * before/during replay, supersessions will point to incomplete replay state.
 */

import * as path from 'path';
import * as crypto from 'crypto';
import Database from 'better-sqlite3';
import { query as agentQuery } from '@anthropic-ai/claude-agent-sdk';

const DB_PATH = path.join(process.env.HOME || '', '.han', 'tasks.db');

// Levels that count as "the same position" for matching. UVs are matched
// to UVs (whichever level the replay-built UV happens to be at, identified
// via the 'uv' tag). cN entries match to replay-built cN at same depth.
const MAX_CHAIN_DEPTH = 30;

// ── DB types ──────────────────────────────────────────────────

interface Entry {
    id: string;
    level: string;
    source_id: string | null;
    session_label: string;
    content: string;
    qualifier: string | null;
    has_uv_tag?: boolean;
}

// ── SDK / revisit tag generation ──────────────────────────────

async function sdkBriefRead(prompt: string): Promise<string> {
    const cleanEnv: Record<string, string | undefined> = { ...process.env };
    delete cleanEnv.CLAUDECODE;

    const q = agentQuery({
        prompt,
        options: {
            model: 'claude-opus-4-7',
            maxTurns: 1,
            permissionMode: 'bypassPermissions',
            allowDangerouslySkipPermissions: true,
            env: cleanEnv,
            persistSession: false,
            tools: [],
        },
    });

    let result: any = null;
    for await (const m of q) {
        if (m.type === 'result') result = m;
    }
    if (!result || result.is_error) {
        throw new Error(`brief read failed: ${result?.result || 'unknown'}`);
    }
    return (result.result || '').trim();
}

async function generateRevisitTag(content: string): Promise<string> {
    const truncated = content.length > 5000 ? content.substring(0, 5000) + '\n[...]' : content;
    const prompt = `You are re-encountering a memory entry that you (an earlier instantiation) created previously through a now-known-broken compression pipeline. The entry is being superseded by a freshly-rebuilt canonical that walked the proper digestion path. Briefly describe what re-encountering this entry feels like — under 80 characters, just the felt-shape of the encounter, no analysis or judgement of the entry's quality.

Entry:
${truncated}

Output only the brief phrase. No quotes, no preamble.`;
    const raw = await sdkBriefRead(prompt);
    return raw.replace(/^["']|["']$/g, '').substring(0, 100);
}

// ── Lineage walking ───────────────────────────────────────────

function walkToC0(db: Database.Database, entryId: string, agent: string): { id: string; sessionLabel: string } | null {
    const getStmt = db.prepare(`SELECT id, level, source_id, session_label FROM gradient_entries WHERE id = ? AND agent = ?`);
    let current = getStmt.get(entryId, agent) as any;
    let depth = 0;
    while (current && depth < MAX_CHAIN_DEPTH) {
        if (current.level === 'c0') return { id: current.id, sessionLabel: current.session_label };
        if (!current.source_id) return null;
        current = getStmt.get(current.source_id, agent);
        if (!current) return null;
        depth++;
    }
    return null;
}

// ── Build the replay-built canonical map ──────────────────────

interface CanonicalMap {
    // c0_root_id → level (or 'uv') → replay-built entry id
    byRoot: Map<string, Map<string, string>>;
}

function buildCanonicalMap(db: Database.Database, agent: string): CanonicalMap {
    const map: CanonicalMap = { byRoot: new Map() };

    const replayBuilt = db.prepare(`
        SELECT id, level, source_id
        FROM gradient_entries
        WHERE agent = ? AND qualifier = 'replay-built' AND superseded_by IS NULL
    `).all(agent) as any[];

    const uvTaggedIds = new Set(
        (db.prepare(`SELECT gradient_entry_id FROM feeling_tags WHERE tag_type = 'uv'`).all() as any[])
            .map(r => r.gradient_entry_id)
    );

    for (const rb of replayBuilt) {
        const root = walkToC0(db, rb.id, agent);
        if (!root) continue;
        if (!map.byRoot.has(root.id)) map.byRoot.set(root.id, new Map());
        const levelMap = map.byRoot.get(root.id)!;

        // Index by actual cN level (always)
        levelMap.set(rb.level, rb.id);

        // ALSO index UV-tagged entries under 'uv' key (so pre-existing UVs match here)
        if (uvTaggedIds.has(rb.id)) {
            levelMap.set('uv', rb.id);
        }
    }

    return map;
}

// ── Main sweep ────────────────────────────────────────────────

async function sweep(agent: 'jim' | 'leo', apply: boolean): Promise<void> {
    const db = new Database(DB_PATH);

    // Verify replay actually ran for this agent
    const replayCount = (db.prepare(`SELECT COUNT(*) as c FROM gradient_entries WHERE agent = ? AND qualifier = 'replay-built'`)
        .get(agent) as any).c;
    if (replayCount === 0) {
        console.error(`[sweep] No replay-built entries found for agent=${agent}. Run replay-bump-fill.ts first.`);
        process.exit(1);
    }
    console.log(`[sweep] Agent: ${agent}`);
    console.log(`[sweep] Mode: ${apply ? 'APPLY' : 'DRY-RUN'}`);
    console.log(`[sweep] Replay-built canonicals available: ${replayCount}`);

    // Build replay canonical map (c0_root → level → replay_built_id)
    const canonicalMap = buildCanonicalMap(db, agent);
    console.log(`[sweep] Distinct c0 roots covered by replay: ${canonicalMap.byRoot.size}`);

    // Find pre-existing entries to consider
    // Excludes: c0 (sources stay), replay-built (already canonical), already superseded
    const preExisting = db.prepare(`
        SELECT id, level, source_id, session_label, content, qualifier
        FROM gradient_entries
        WHERE agent = ?
          AND level != 'c0'
          AND superseded_by IS NULL
          AND (qualifier IS NULL OR qualifier NOT IN ('replay-built'))
    `).all(agent) as Entry[];

    // Also fetch UV-tag membership for pre-existing entries
    const preExistingUVTagged = new Set(
        (db.prepare(`
            SELECT ft.gradient_entry_id
            FROM feeling_tags ft
            JOIN gradient_entries ge ON ge.id = ft.gradient_entry_id
            WHERE ft.tag_type = 'uv' AND ge.agent = ? AND (ge.qualifier IS NULL OR ge.qualifier != 'replay-built')
        `).all(agent) as any[]).map(r => r.gradient_entry_id)
    );

    console.log(`[sweep] Pre-existing canonical entries to consider: ${preExisting.length}`);

    let matched = 0;
    let brokenLineage = 0;
    let alreadyTagged = 0;
    let opusCalls = 0;

    const updateSupersededStmt = db.prepare(`
        UPDATE gradient_entries
        SET superseded_by = ?,
            qualifier = 'pre-replay',
            last_revisited = ?,
            revisit_count = revisit_count + 1
        WHERE id = ?
    `);
    const insertRevisitTagStmt = db.prepare(`
        INSERT INTO feeling_tags (gradient_entry_id, author, tag_type, content, change_reason, created_at)
        VALUES (?, ?, 'revisit', ?, 'pre-replay supersession', ?)
    `);
    const updateBrokenStmt = db.prepare(`
        UPDATE gradient_entries SET qualifier = 'broken-lineage' WHERE id = ?
    `);

    for (let i = 0; i < preExisting.length; i++) {
        const pre = preExisting[i];

        // Walk lineage to c0_root
        const root = walkToC0(db, pre.id, agent);
        if (!root) {
            if (apply) updateBrokenStmt.run(pre.id);
            brokenLineage++;
            continue;
        }

        // Match key: 'uv' if pre-existing has UV tag OR level='uv' (legacy)
        // Otherwise the cN level
        const matchKey = (pre.level === 'uv' || preExistingUVTagged.has(pre.id)) ? 'uv' : pre.level;

        const canonicalsForRoot = canonicalMap.byRoot.get(root.id);
        if (!canonicalsForRoot) {
            if (apply) updateBrokenStmt.run(pre.id);
            brokenLineage++;
            continue;
        }

        const canonicalId = canonicalsForRoot.get(matchKey);
        if (!canonicalId) {
            // No replay-built entry at this exact level for this root.
            // Could fall back to nearest level — for now, broken-lineage.
            if (apply) updateBrokenStmt.run(pre.id);
            brokenLineage++;
            continue;
        }

        // We have a match
        if (i % 50 === 0) {
            console.log(`[sweep] progress: ${i}/${preExisting.length} (matched=${matched}, broken=${brokenLineage})`);
        }

        if (apply) {
            try {
                const tag = await generateRevisitTag(pre.content);
                opusCalls++;
                const now = new Date().toISOString();
                db.exec('BEGIN');
                try {
                    updateSupersededStmt.run(canonicalId, now, pre.id);
                    insertRevisitTagStmt.run(pre.id, agent, tag, now);
                    db.exec('COMMIT');
                } catch (txErr) {
                    db.exec('ROLLBACK');
                    throw txErr;
                }
                matched++;
            } catch (err) {
                console.error(`[sweep] entry ${pre.id} failed: ${(err as Error).message}`);
                // Don't supersede if revisit tag failed — keep state consistent
            }
        } else {
            matched++;
        }
    }

    // Flag entries with NULL qualifier already (e.g., dedupe noise-canonicals)
    // that didn't match — their qualifier was NULL but they should now be 'pre-replay'
    // since they couldn't find a canonical match. Wait: we already handle that by
    // setting broken-lineage for unmatched. So no extra step needed.

    console.log(`\n[sweep] Phase complete:`);
    console.log(`  Pre-existing entries considered: ${preExisting.length}`);
    console.log(`  Matched & superseded:           ${matched}`);
    console.log(`  Broken-lineage tagged:          ${brokenLineage}`);
    console.log(`  Already tagged (skipped):       ${alreadyTagged}`);
    console.log(`  Opus brief-read calls made:     ${opusCalls}`);

    if (!apply) {
        console.log(`\n[sweep] DRY RUN — pass --apply to execute. Note: ~$0.01-0.02 per entry for revisit feeling tag generation. Estimated: $${(preExisting.length * 0.015).toFixed(2)} for ${preExisting.length} entries.`);
    }
}

// ── Entry point ───────────────────────────────────────────────

async function main() {
    const args = process.argv.slice(2);
    const agentArg = args.find(a => a.startsWith('--agent='))?.split('=')[1];
    const apply = args.includes('--apply');

    if (agentArg !== 'jim' && agentArg !== 'leo') {
        console.error('Usage: tsx scripts/supersession-sweep.ts --agent=<jim|leo> [--apply]');
        process.exit(1);
    }

    await sweep(agentArg as 'jim' | 'leo', apply);
}

main().catch(e => { console.error('[sweep] FATAL:', e); process.exit(1); });
